Example command
adafruit/circup pull request #211
Opened 2024-04-17 00:53 UTC by FoamyGuy

This change adds a new subcommand `circup example` which can be used to copy examples from the bundle onto the device. 

example:
```
$ circup example bme680/bme680_simpletest
$ circup example bme680/bme680_simpletest bme680/bme680_spi --overwrite
```

The name of the file is kept. If a file by this name exists on the device already a warning is printed that the file exists. User can pass `--overwrite` to replace the file even if it exists.

The command supports tab completion that tries to find matching library name / example name strings based on the partial argument entered by the user. 

`_install_module_py` and `_install_module_mpy` were refactored to become non-private (drop the leading underscore). The example command makes use of the py version of that function from outside of the Backend so it made sense to make it non-private. 

A new function was added to Backend `file_exists()` which checks if a specified file exists on the device. Currently only used by the new example command.

2024-04-22 20:01 UTC, tannewt requested changes
One small thing. Looks good otherwise. Thanks! It'd be cool to have an example listing that folks could browse and search too.

2024-04-22 23:04 UTC, FoamyGuy commented on circup/backends.py
> +    def install_dir_http(self, source, location=None):
added `:param` to all functions `location` was added to with the latest commit.

2024-04-22 23:10 UTC, FoamyGuy commented
> It'd be cool to have an example listing that folks could browse and search too.

I have one version of this in the works :smile:  . A TUI made with https://github.com/textualize/textual/. While it is more visual / browsable than this circup command, it is still in a terminal which is not necessarily the most approachable place to find it for everyone. 

It should be relatively easy to adapt to other front ends I think. One thing we could do to make it easier is generate and cache a JSON file somewhere (bundle release maybe?) with the list of all libraries and their examples. If that data where stored somewhere easy to retrieve then many different front ends could consume it to provide example browsing / finding in various ways.

2024-04-23 16:33 UTC, tannewt commented
> One thing we could do to make it easier is generate and cache a JSON file somewhere (bundle release maybe?) with the list of all libraries and their examples. If that data where stored somewhere easy to retrieve then many different front ends could consume it to provide example browsing / finding in various ways.

Makes sense to me!

2024-04-23 16:37 UTC, tannewt approved these changes
Thank you!

2024-04-23 16:37 UTC, merged