Adding option to install library stubs from PyPi
adafruit/circup pull request #229
Opened 2024-06-17 11:49 UTC by Jessseee

Implementation of feature requested #140, this is something I would really like to see as a PyCharm user. 

As described in the [PyCharm + CircuitPython setup guide](https://learn.adafruit.com/welcome-to-circuitpython/pycharm-and-circuitpython) there are packages available on PyPi that contain stubs for libraries from the Adafruit Library Bundle, these packages help give the IDE you are using context for your CircuitPython code so that code hinting can work properly.

Instead of having to manually install these stubs after installing packages using CircUp, this PR adds the `--stubs` flag to the `circup install` command which enables a step in the installation process to try to install the available stubs package using `pip`.

This would currently only work for libraries in the Adafruit CircuitPython Bundle, as I don't see an easy way to find out whether there are stubs packages on PyPi for any other CircuitPython libraries.

2024-06-17 16:21 UTC, FoamyGuy requested changes
Thanks for adding this functionality @Jessseee

I think this should not be in the Backend class. Backend and it's sub-classes are meant to contain only functionality that needs to interact with CircuitPython devices. 

Since the new functionality is installing stubs on the PC that is running circup rather than doing anything to the Circuitpython device that is connected I think it would be best to move it somewhere else. 

In my mind having the new functionality inside of `install()` function in commands.py would be a good spot for this. https://github.com/adafruit/circup/blob/main/circup/commands.py#L314

2024-06-17 16:23 UTC, Jessseee commented
Ah yes, I was debating where to put it, but with that explanation, it would indeed make more sense to put it in the install command.

2024-06-17 18:37 UTC, Jessseee commented
@FoamyGuy Moved the installation of the stubs packages to `commands.py` and reverted any changes I made to `backends.py`. Sorry for spamming the CI, I had a small fight with your pre-commit pipeline. 😅

2024-07-01 20:38 UTC, FoamyGuy approved these changes
Looks good to me. Thanks again for adding this @Jessseee!

I tested this branch successfully in a local venv.

2024-07-01 20:39 UTC, merged